<a href="https://colab.research.google.com/github/sivarajpdm/OCIGenAIChat/blob/main/numpy_and_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [ ]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [ ]:
element_wise_product = A * B
# Or using np.multiply
# element_wise_product = np.multiply(A, B)
display(element_wise_product)

array([[ 5, 12],
       [21, 32]])

In [ ]:
L1=[1,2,3,4,5]
L2=[5,6,7,8,9]
L1+L2
print(type(L1))

import numpy as np
arr1 =np.array([[1,2], [3,4]])
arr2=np.array([[3,4], [5,6]])

arr1+arr2
print(arr1*arr2)

<class 'list'>
[[ 3  8]
 [15 24]]


In [ ]:
print(L1[4])

5


In [ ]:
mat = np.array([[1, 2], [3, 4]])
mat[0, 1]     # 2

np.int64(2)

In [46]:
import pandas as pd

d = {'people':['P1','P2','P3'] , 'age' :[20,30,40]}
print(d)

df = pd.DataFrame(d)
print(df)

pd.read_excel("score_updated.xlsx")

{'people': ['P1', 'P2', 'P3'], 'age': [20, 30, 40]}
  people  age
0     P1   20
1     P2   30
2     P3   40


FileNotFoundError: [Errno 2] No such file or directory: 'score_updated.xlsx'

As you can see, each element in the resulting matrix is the product of the corresponding elements from matrices `A` and `B`.